# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET Build and Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0 # avoid shallow clone so nbgv can do its work.
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: |
        dotnet restore StreamDeckSimHub.Plugin/StreamDeckSimHub.Plugin.csproj
        dotnet restore StreamDeckSimHub.PluginTests/StreamDeckSimHub.PluginTests.csproj
    - name: Build
      run: |
        dotnet build --no-restore StreamDeckSimHub.Plugin/StreamDeckSimHub.Plugin.csproj
        dotnet build --no-restore StreamDeckSimHub.PluginTests/StreamDeckSimHub.PluginTests.csproj
    - name: Test
      run: |
        dotnet test --no-build --verbosity normal StreamDeckSimHub.PluginTests/StreamDeckSimHub.PluginTests.csproj
